services:
  backend:
    image: ${IMAGE_REPOSITORY:-thisisbash/bookshop-st2}:${IMAGE_TAG:?IMAGE_TAG is required for prod}
    restart: always

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8003:8000"

    networks:
      - bookshopnet

  db:
    image: postgres:15
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - bookshopnet

volumes:
  postgres_data:

networks:
  bookshopnet:
    driver: bridge
