services:
  backend:
    build: .
    restart: always

    env_file:
      - .env.example
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - bookshopnet
  db:
    image: postgres:15
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tempUser -d bookshopdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env.example
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookshopnet


volumes:
  postgres_data:

networks:
  bookshopnet:
    driver: bridge
